config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'posts#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:index, :new, :create]
  
  resources :posts, only: [:index, :show, :new, :create] do
    resources :responses, only: [:create]
    resource :post_category_relationships, only: [:create]
    get :category
  end

  resources :categories, only: [:index, :new, :create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_category_relations
  has_many :posts, through: :post_category_relations
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { maximum: 20 }, presence: true
  validates :content, length: { maximum: 2000 }, presence: true

  belongs_to :user

  has_many :responses
  has_many :post_category_relations
  has_many :categories, through: :post_category_relations
end

app/models/post_category_relation.rb
class PostCategoryRelation < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts
  has_many :responses
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.new
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save!
      redirect_to new_post_path
    else
      @categories = Category.all
      render 'index'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/post_category_relations_controller.rb
class PostCategoryRelationsController < ApplicationController
  def create
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @search = Post.ransack(params[:q])
    @posts = @search.result
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @responses = @post.responses
    @response = Response.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render 'posts/new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, { category_ids: [] })
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :set_post

  def create
    post = Post.find(params[:post_id])
    response = current_user.responses.build(response_params)
    response.post_id = post.id
    
    redirect_to post_path(post.id) if response.save
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def response_params
    params.require(:response).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, if: proc{action_name=="new" || action_name=="create"}

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id unless current_user
      redirect_to root_path, notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/post_category_relations_helper.rb
module PostCategoryRelationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.slim
h1 カテゴリー一覧

= form_with model: @category, local: true do |f|

  = f.label :name, 'カテゴリー名'
  br
  = f.text_field :name, class:'form-control'
  br

  = f.submit '追加', class: 'btn btn-primary'

app/views/categories/new.html.slim
h1 カテゴリ作成

= form_with model: @category, local: true, class: 'form-horizontal' do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  = f.submit class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MyBbs
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    = render 'shared/header'
    .container
      = yield
    = render 'shared/footer'

app/views/post_category_relations/create.html.slim
h1 PostCategoryRelations#create
p Find me in app/views/post_category_relations/create.html.slim

app/views/posts/index.html.slim
h1 投稿一覧

body
  .input-group
    = search_form_for @search, url: posts_path do |f|
      .input-group
        = f.search_field :content_cont, placeholder: '単語検索はこちら',class: 'form-control'
        .input-group-button
          = f.submit '検索', class: 'btn btn-primary'
  <br>
  .btn.btn-outline-link.btn-lg
    = link_to '新規投稿はこちら', new_post_path
  <br>
  <br>
  - @posts.each do |post|
    .card.card-body
      h5.card-titles 
        = "「#{post.title}」"
      h6.card-subtitle.mb-2.text-muted  
        = "投稿者: #{post.user.name} さん"
      p.card-text
        = post.content
      h6.card-subtitle.mb-2.text-muted
        = post.created_at.strftime('%Y年%m月%d日 %H:%M')
      h7.card-subtitle.mb-2.text-muted
        - post.post_category_relations.each do |c|
          .badge.badge-info
            = c.category.name
      p.card-text
        = link_to post_path(post) do
            svg.bi.bi-chat[width="1em" height="1em" viewbox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg"]
                path[fill-rule="evenodd" d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"]
        = post.responses.count

app/views/posts/new.html.slim
h1 投稿作成

= form_with model: @post, local: true, class: 'form-horizontal' do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10
  .form-group
    = f.label :category_id, 'カテゴリー'
    = f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category|
      = category.label do
        .badge.badge-info
          = category.check_box
          = category.text
  = f.submit class: 'btn btn-primary'
  <br>
  <br>
  = link_to 'カテゴリの新規作成はこちら', new_category_path

app/views/posts/show.html.slim
h1 投稿詳細

body
  .card.card-body
    h4.card-titles 
      = "「#{@post.title}」"
    p.card-text
      = @post.content
    h7.card-subtitle.mb-2.text-muted  
      = "by #{@post.user.name} さん"
    h9.card-subtitle.mb-2.text-muted
      = @post.created_at.strftime('%Y年%m月%d日 %H:%M')
<br>

h2 コメント一覧
- @responses.each do |res|
  .card.card-body
      p.card-text
        = res.content
      h7.card-subtitle.mb-2.text-muted  
        = "by #{res.user.name} さん"
      h9.card-subtitle.mb-2.text-muted  
        = res.created_at.strftime('%Y年%m月%d日 %H:%M')
<br>

h3 新規コメント作成
= form_with model: [@post, Response.new], local: true do |f|
  = f.text_area :content, class: 'form-control', row: 10
  = f.submit 'コメントする', class: 'btn btn-primary'

app/views/responses/new.html.slim
h1 投稿作成

= form_with model: @response, local: true, class: 'form-horizontal' do |f|
  .form-group
    = f.label @current_user.name
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control', row: 10
  = f.submit class: 'btn btn-primary'

app/views/shared/_footer.html.slim
footer.col-text-center
  p &copy; 2020 Bonzo

app/views/shared/_header.html.slim
header.navbar.navbar-expand.navbar-light.bg-light
  .container
    = link_to 'MyBBS', root_path, class: 'navbar-brand'
    ul.navbar-nav
      - if current_user
        li.nav-item= link_to '投稿一覧', posts_path, class: 'nav-link'
        li.nav-item= link_to 'ユーザー一覧', users_path, class: 'nav-link'
        li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
      - else
        li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

app/views/users/index.html.slim
h1 ユーザー一覧

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= user.email
        td= user.created_at
        td= user.updated_at

app/views/users/new.html.slim
h1 ユーザー登録

= form_with model: @user, local: true, class: 'form-horizontal' do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit class: 'btn btn-primary'